apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-nginx-config
    namespace: learndev
data:
    nginx.conf: |
        upstream learndev {
            server learndev-service.learndev.svc.cluster.local:80;
        }

         
        # upstream ecommerce {
        #     server ecommerce-service.learndev.svc.cluster.local:80;
        # }

        upstream django-notes-service {
            server django-notes-service-service.learndev.svc.cluster.local:80;
        }


        server {
            listen 80;
            server_name _;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # learndev app at /
            location / {
                proxy_pass http://learndev;
            }

            # Add ecommerce upstream and location block here once
            # ecommerce-service is deployed to the cluster:
            
            # upstream ecommerce {
            #     server ecommerce-service.learndev.svc.cluster.local:80;
            # }
            # location /ecommerce {
            #     proxy_pass http://ecommerce;
            # }

            location /django-notes {
                proxy_pass http://django-notes-service;
            }
        }
