apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-nginx-config
    namespace: learndev
data:
    nginx.conf: |
        upstream learndev {
            server learndev-service.learndev.svc.cluster.local:80;
        }

        upstream django-notes {
            server django-notes-service.learndev.svc.cluster.local:80;
        }

        server {
            listen 80;
            server_name _;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # learndev app
            location / {
                proxy_pass http://learndev;
            }

            # django-notes app (FIXED)
            location /django-notes/ {
                proxy_pass http://django-notes/;
            }
        }
